version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
    working_directory: ~/dynamic_prints
    environment:
    steps:
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main